sudo: false
language: node_js
node_js:
  - node
services:
  - mongodb
  - redis-server
cache:
  directories:
    - node_modules
env:
  - CROWDSOURCE_CONFIG_FILE=./config.travis.json
before_install:
  - openssl aes-256-cbc -K $encrypted_d9ec00f8c0f2_key -iv $encrypted_d9ec00f8c0f2_iv
    -in config.travis.json.enc -out config.travis.json -d
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
  - npm run docs
deploy:
  provider: pages
  local_dir: dist/crowdsourcing-platform-server
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: dev
